// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rydsmftbvymncpndqctg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5ZHNtZnRidnltbmNwbmRxY3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwOTg0NjYsImV4cCI6MjA1NzY3NDQ2Nn0.4_hIH5I6k3mgNn_KtlrvQhXi0yFhzhbbwV4j6rX43R0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);