// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxxqusktooxnlxhjkuuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94eHF1c2t0b294bmx4aGprdXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDE2MTUsImV4cCI6MjA1NzY3NzYxNX0.nJThGyHcA4cFGf16xOVJ2Mc1oSp22gMxXc5KUW7zD6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);